# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhXWUI5OV5TkaYZVJuuCJ3f1mhxuJU8t
"""

import pandas as pd

df = pd.read_csv("/content/ICD-SNOMEDCT.csv",encoding='latin1')

df.head(5)

df1=pd.read_csv("/content/dr_min_data(1).csv")

df1.head(5)

df

##df['SNOMED_CID'] = df['SNOMED_CID'].str.replace('.','')
###df['SNOMED_CID']

columns_to_select = ('diagnosis1', 'diagnosis2', 'diagnosis3', 'diagnosis4', 'diagnosis5')

# Select columns using the tuple
selected_columns = df1[list(columns_to_select)]

for k in selected_columns:
  if "." in k:
    print("dot:",k)
  else:
    print(k)

df['ICD_CODE'] = df['ICD_CODE'].str.replace('.','')
df['ICD_CODE']

df

##df_join = df1.merge(df, left_on='diagnosis1', right_on='SNOMED_CID')

df_join1 = df1.merge(df, left_on='diagnosis1',right_on='ICD_CODE', how='left')
df_join2 = df1.merge(df, left_on='diagnosis2',right_on='ICD_CODE', how='left')
df_join3 = df1.merge(df, left_on='diagnosis3',right_on='ICD_CODE', how='left')
df_join4 = df1.merge(df, left_on='diagnosis4',right_on='ICD_CODE', how='left')
df_join5 = df1.merge(df, left_on='diagnosis5',right_on='ICD_CODE', how='left')

df_join1

#df_join1['patient_id'].nunique()
#df_join2['patient_id'].nunique()
#df_join3['patient_id'].nunique()
#df_join4['patient_id'].nunique()
#df_join5['patient_id'].nunique()

df_join2 .columns

column_1 = ['patient_id','diagnosis1','SNOMED_CID']
 column_2 = ['patient_id','diagnosis2','SNOMED_CID']
 column_3 = ['patient_id','diagnosis3','SNOMED_CID']
 column_4 = ['patient_id','diagnosis4','SNOMED_CID']
 column_5 = ['patient_id','diagnosis5','SNOMED_CID']

df_map1 = pd.DataFrame(list(df_join1.groupby(column_1).groups),columns=column_1)
df_map1.rename(columns={'SNOMED_CID':'SNOMED_CID1'}, inplace=True)
df_map2 = pd.DataFrame(list(df_join2.groupby(column_2).groups), columns= column_2)
df_map2.rename(columns={'SNOMED_CID':'SNOMED_CID2'}, inplace=True)
df_map3 = pd.DataFrame(list(df_join3.groupby(column_3).groups), columns= column_3)
df_map3.rename(columns={'SNOMED_CID':'SNOMED_CID3'}, inplace=True)
df_map4 = pd.DataFrame(list(df_join4.groupby(column_4).groups), columns= column_4)
df_map4.rename(columns={'SNOMED_CID':'SNOMED_CID4'}, inplace=True)
df_map5 = pd.DataFrame(list(df_join5.groupby(column_5).groups), columns= column_5)
df_map5.rename(columns={'SNOMED_CID':'SNOMED_CID5'}, inplace=True)

df_map1



merged_df_map = df_map1.merge(df_map2, how='outer').merge(df_map3, how='outer').merge(df_map4, how='outer').merge(df_map5, how='outer')

merged_df_map.drop_duplicates(inplace=True)

merged_df_map

merged_df_map .to_csv("/content/snomed.csv")